### ISSUE TITLE
能否提供maven版本的项目支持

### ISSUE THREAD

**Issue by ylh23y** [helloworlde/spring-cloud-alibaba-component#3]
能否提供maven版本的项目支持pom.xml

**Comment by helloworlde** [comment]
不考虑转用 Maven，太冗余且模块不好组织，需要的话可以自己添加Maven的 plugin，会自动生成，再手动修改下就好了

**Comment by ylh23y** [comment]
怎么“自己添加Maven的 plugin，会自动生成”？

**Comment by helloworlde** [comment]
@ylh23y 
参考 https://docs.gradle.org/current/userguide/maven_plugin.html
